# Generated by Django 4.1.7 on 2023-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='pul',
            field=models.IntegerField(default=60),
        ),
    ]
