# Generated by Django 4.1.7 on 2023-04-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
